import { jsPDF } from 'jspdf';
import { Chart, registerables } from 'chart.js';

// Register all Chart.js components
Chart.register(...registerables);

/**
 * Fetches state distribution data from the backend API
 * @returns {Promise<Array>} - Array of state distribution data points
 */
export async function fetchStateDistributionData() {
  try {
    const response = await fetch('http://localhost:3001/api/tracking/state-distribution?limit=50');
    const result = await response.json();
    
    if (result.success && result.data) {
      return result.data;
    }
    
    console.warn('No state distribution data found');
    return [];
  } catch (error) {
    console.error('Error fetching state distribution data:', error);
    throw error;
  }
}

/**
 * Creates a canvas element with the active vs idle line chart
 * @param {Array} data - State distribution data
 * @returns {HTMLCanvasElement} - Canvas element with chart
 */
function createLineChartCanvas(data) {
  // Create a temporary canvas
  const canvas = document.createElement('canvas');
  canvas.width = 800;
  canvas.height = 400;
  document.body.appendChild(canvas);

  // Prepare data for the chart
  const labels = data.map(d => d.hour || new Date(d.time).toLocaleTimeString());
  const activeData = data.map(d => d.isActive);
  const idleData = data.map(d => d.isIdle);

  // Create the chart
  new Chart(canvas, {
    type: 'line',
    data: {
      labels: labels,
      datasets: [
        {
          label: 'Active',
          data: activeData,
          borderColor: 'rgb(75, 192, 192)',
          backgroundColor: 'rgba(75, 192, 192, 0.2)',
          tension: 0.3,
          fill: true
        },
        {
          label: 'Idle',
          data: idleData,
          borderColor: 'rgb(255, 99, 132)',
          backgroundColor: 'rgba(255, 99, 132, 0.2)',
          tension: 0.3,
          fill: true
        }
      ]
    },
    options: {
      responsive: false,
      maintainAspectRatio: false,
      plugins: {
        title: {
          display: true,
          text: 'Active vs Idle States Over Time',
          font: {
            size: 18
          }
        },
        legend: {
          position: 'top'
        }
      },
      scales: {
        y: {
          beginAtZero: true,
          title: {
            display: true,
            text: 'Count'
          }
        },
        x: {
          title: {
            display: true,
            text: 'Time'
          }
        }
      }
    }
  });

  return canvas;
}

/**
 * Generates a PDF report with active vs idle line chart
 * @param {Array} data - Optional data array, if not provided will fetch from API
 * @returns {Promise<Blob>} - PDF blob
 */
export async function generateActivityPdfReport(data = null) {
  try {
    // Fetch data if not provided
    let chartData = data;
    if (!chartData || chartData.length === 0) {
      chartData = await fetchStateDistributionData();
    }

    if (chartData.length === 0) {
      throw new Error('No data available to generate chart');
    }

    // Create the chart on a canvas
    const canvas = createLineChartCanvas(chartData);

    // Wait for the chart to render
    await new Promise(resolve => setTimeout(resolve, 500));

    // Get image data from canvas
    const chartImage = canvas.toDataURL('image/png', 1.0);

    // Remove the temporary canvas
    document.body.removeChild(canvas);

    // Create PDF document
    const pdf = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: 'a4'
    });

    // Add title
    pdf.setFontSize(20);
    pdf.setTextColor(44, 62, 80);
    pdf.text('Activity Report: Active vs Idle States', 15, 20);

    // Add date
    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    pdf.text(`Generated: ${new Date().toLocaleString()}`, 15, 28);

    // Add summary statistics
    const activeCount = chartData.filter(d => d.isActive).length;
    const idleCount = chartData.filter(d => d.isIdle).length;
    const totalPoints = chartData.length;

    pdf.setFontSize(12);
    pdf.setTextColor(0, 0, 0);
    pdf.text(`Total Data Points: ${totalPoints}`, 15, 40);
    pdf.text(`Active States: ${activeCount} (${Math.round((activeCount / totalPoints) * 100)}%)`, 15, 48);
    pdf.text(`Idle States: ${idleCount} (${Math.round((idleCount / totalPoints) * 100)}%)`, 15, 56);

    // Add the chart image
    const imgWidth = 250;
    const imgHeight = 120;
    pdf.addImage(chartImage, 'PNG', 15, 65, imgWidth, imgHeight);

    // Add footer
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text('Generated by Employee Activity Tracker', 15, 185);

    // Return the PDF as a blob
    return pdf.output('blob');
  } catch (error) {
    console.error('Error generating PDF report:', error);
    throw error;
  }
}

/**
 * Downloads the PDF report directly
 * @param {string} filename - Optional filename
 * @param {Array} data - Optional data array
 */
export async function downloadActivityPdfReport(filename = 'activity-report.pdf', data = null) {
  try {
    const pdfBlob = await generateActivityPdfReport(data);
    
    // Create download link
    const url = URL.createObjectURL(pdfBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Clean up
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error('Error downloading PDF report:', error);
    throw error;
  }
}
